In [7]:
import pandas as pd
print("Pandas working fine")

Pandas working fine

In [8]:
import os 
import pandas as pd 
from docx import Document
resume_folder ="../Resumes"
files = os.listdir(resume_folder)
print("Total number of resumes: ", len(files))
print("First 5 resumes: ", files[:5])

Total number of resumes:  228
First 5 resumes:  ['Abiral_Pandey_Fullstack_Java.docx', 'Achyuth Resume_8.docx', 'Adelina_Erimia_PMP1.docx', 'Adhi Gopalam - SM.docx', 'AjayKumar.docx']

In [9]:
sample_resume = files[0]
resume_path = os.path.join(resume_folder, sample_resume)
print("Reading resume: ")
print(resume_path)
doc = Document(resume_path)
resume_text = ""
for para in doc.paragraphs:
    resume_text += para.text + "\n"
print("\nResume Text: \n")
print(resume_text[:1000])  # Print first 1000 characters of the resume text

Reading resume:
../Resumes\Abiral_Pandey_Fullstack_Java.docx

Resume Text:

Name: Abiral Pandey
Email: abiral.pandey88@gmail.com
Phone: 940-242-3303
Current Location: Woonsocket, Rhode Island
Visa Status: US Citizen

SUMMARY:
Dynamic individual with 6 years of software development experience in design, development, deployment, maintenance, production and support of web - based and Client-Server business applications using OOP and Java/J2EE technologies.
Exposure to all phases of Software Development Life Cycle(SDLC) using Agile, RUP, Waterfall.
Designed and developed web UI screen using Angular-JS.
Developed AngularJS Controllers, Services, filters and directives for various modules in the application.
Knowledge on ETL tools like Kettle Pentaho and Microsoft SSIS tools.
Created custom directives, decorators and services using AngularJS to interface with both RESTful and legacy network services also DOM applications.
Experience with MVC frameworks like Struts, SPRING and ORM tools like Hibernate.
Experienced in working with batch jobs using Spring-Batch, Autosy

In [10]:
resume_data = []
for file in files:
    file_path = os.path.join(resume_folder, file)
    try:
        doc = Document(file_path)
        text = ""
        for para in doc.paragraphs:
            text += para.text + "\n"
        resume_data.append({"filename": file, "resume_text": text})
    except Exception as e:
        print(f"Error reading {file}: {e}")
df = pd.DataFrame(resume_data)
print("DataFrame created with resume data:")
print("Total resumes processed: ", len(df))
df

DataFrame created with resume data:
Total resumes processed:  228

,filename,resume_text
0,Abiral_Pandey_Fullstack_Java.docx,Name: Abiral Pandey\nEmail: abiral.pandey88@gm...
1,Achyuth Resume_8.docx,Achyuth\n540-999-8048\nachyuth.java88@gmail.co...
2,Adelina_Erimia_PMP1.docx,"Adelina Erimia, PMP, Six Sigma Green Belt, SMC..."
3,Adhi Gopalam - SM.docx,Adhi Gopalam\nadhigopalam@gmail.com\n281-212-3...
4,AjayKumar.docx,Ajay Kumar (CSM)\t \t\t Email/Skype: a...
...,...,...
223,Vishnu Java dev.docx,VISHNU J\nEmail to jammigumpulavishnu452@gmail...
224,Vivek Joshi_CV.docx,"\nVivek Joshi\nBusiness Analyst\nBellevue, WA\..."
225,Vivek.BSA.docx,VIVEK SAGAR ...
226,Yohan BSA.docx,"YOHAN \nSr. Business Analyst\n\nVersatile, eff..."
227,Yugesh_Resume.docx,Yugesh\n+1(515)-650-2459\nyugeshm4@gmail.com\n...

In [11]:
def create_category(filename):
    filename = filename.lower()
    if "java" in filename:
        return "Java Developer" 
    elif "python" in filename:
        return "Python Developer"
    elif "analyst" in filename:
        return "Data Analyst"
    elif "developer" in filename:
        return "Software Developer"
    elif "manager" in filename:
        return "Project Manager"
    else:
        return "Other"
df["category"] = df["filename"].apply(create_category)
df[["filename", "category"]].head(20)

                             filename            category
0   Abiral_Pandey_Fullstack_Java.docx      Java Developer
1               Achyuth Resume_8.docx               Other
2            Adelina_Erimia_PMP1.docx               Other
3              Adhi Gopalam - SM.docx               Other
4                      AjayKumar.docx               Other
5                  Akhil.profile.docx               Other
6                   Akhil_Sr BSA.docx               Other
7                 Alekhya Resume.docx               Other
8                    Amar Sr BSA.docx               Other
9                       Ami Jape.docx               Other
10     Amrinder Business Analyst.docx        Data Analyst
11             Amulya Komatineni.docx               Other
12     Anil Krishna Mogalaturthi.docx               Other
13                   AnilAgarwal.docx               Other
14   Anudeep N_Sr Java Developer.docx      Java Developer
15          Ashok Jayakumar - PM.docx               Other
16        Ashwini J2EE Developer.docx  Software Developer
17            Atul_Mathur_Resume.docx               Other
18       Avathika BA-Healthcare_.docx               Other
19                     avinash G.docx               Other

In [12]:
import re 
def clean_resume_text(text):
    text = text.lower() 
    text = re.sub(r'\S+@\S+', ' ', text)  
    text = re.sub(r'd+', ' ', text)
    text = re.sub(r'[^a-zA-Z\s]', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text
df["cleaned_resume_text"] = df["resume_text"].apply(clean_resume_text)
df[["filename", "cleaned_resume_text"]].head()

,filename,cleaned_resume_text
0,Abiral_Pandey_Fullstack_Java.docx,name abiral pan ey email phone current locatio...
1,Achyuth Resume_8.docx,achyuth objective aroun years of strong softwa...
2,Adelina_Erimia_PMP1.docx,a elina erimia pmp six sigma green belt smc pr...
3,Adhi Gopalam - SM.docx,a hi gopalam certifie scrum master an business...
4,AjayKumar.docx,ajay kumar csm email skype mob professional su...

In [13]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
nltk.download('punkt_tab')
nltk.download('punkt')
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))
def preprocess_text(text):
    words = word_tokenize(text)
    filtered_words = [word for word in words if word not in stop_words]
    cleaned_text = ' '.join(filtered_words)
    return cleaned_text
df["processed_resume"] = df["cleaned_resume_text"].apply(preprocess_text)
df[["category","processed_resume"]].head()

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\harsh\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\harsh\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\harsh\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

         category                                   processed_resume
0  Java Developer  name abiral pan ey email phone current locatio...
1           Other  achyuth objective aroun years strong software ...
2           Other  elina erimia pmp six sigma green belt smc proj...
3           Other  hi gopalam certifie scrum master business anal...
4           Other  ajay kumar csm email skype mob professional su...

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_features=5000)
X = tfidf.fit_transform(df["processed_resume"])
y = df["category"]
print("TF-IDF features created. Shape: ", X.shape)
print("Total categories:", y.nunique())
df

TF-IDF features created. Shape:  (228, 5000)
Total categories: 5

,filename,resume_text,category,cleaned_resume_text,processed_resume
0,Abiral_Pandey_Fullstack_Java.docx,Name: Abiral Pandey\nEmail: abiral.pandey88@gm...,Java Developer,name abiral pan ey email phone current locatio...,name abiral pan ey email phone current locatio...
1,Achyuth Resume_8.docx,Achyuth\n540-999-8048\nachyuth.java88@gmail.co...,Other,achyuth objective aroun years of strong softwa...,achyuth objective aroun years strong software ...
2,Adelina_Erimia_PMP1.docx,"Adelina Erimia, PMP, Six Sigma Green Belt, SMC...",Other,a elina erimia pmp six sigma green belt smc pr...,elina erimia pmp six sigma green belt smc proj...
3,Adhi Gopalam - SM.docx,Adhi Gopalam\nadhigopalam@gmail.com\n281-212-3...,Other,a hi gopalam certifie scrum master an business...,hi gopalam certifie scrum master business anal...
4,AjayKumar.docx,Ajay Kumar (CSM)\t \t\t Email/Skype: a...,Other,ajay kumar csm email skype mob professional su...,ajay kumar csm email skype mob professional su...
...,...,...,...,...,...
223,Vishnu Java dev.docx,VISHNU J\nEmail to jammigumpulavishnu452@gmail...,Java Developer,vishnu j email to contact senior java eveloper...,vishnu j email contact senior java eveloper su...
224,Vivek Joshi_CV.docx,"\nVivek Joshi\nBusiness Analyst\nBellevue, WA\...",Other,vivek joshi business analyst bellevue wa busin...,vivek joshi business analyst bellevue wa busin...
225,Vivek.BSA.docx,VIVEK SAGAR ...,Other,vivek sagar sr business system analyst profess...,vivek sagar sr business system analyst profess...
226,Yohan BSA.docx,"YOHAN \nSr. Business Analyst\n\nVersatile, eff...",Other,yohan sr business analyst versatile effective ...,yohan sr business analyst versatile effective ...
227,Yugesh_Resume.docx,Yugesh\n+1(515)-650-2459\nyugeshm4@gmail.com\n...,Other,yugesh professional summary aroun years of exp...,yugesh professional summary aroun years experi...

In [15]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report,accuracy_score
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=44)
model = MultinomialNB()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Model Accuracy: ", accuracy)
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Model Accuracy:  0.9130434782608695

Classification Report:
                 precision    recall  f1-score   support

  Data Analyst       0.00      0.00      0.00         1
Java Developer       0.00      0.00      0.00         3
         Other       0.91      1.00      0.95        42

      accuracy                           0.91        46
     macro avg       0.30      0.33      0.32        46
  weighted avg       0.83      0.91      0.87        46

c:\Users\harsh\SkillScan\mlenv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\harsh\SkillScan\mlenv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\harsh\SkillScan\mlenv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [16]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)
rf_pred = rf_model.predict(X_test)
rf_accuracy = accuracy_score(y_test, rf_pred)
print("Random Forest Model Accuracy: ", rf_accuracy)

Random Forest Model Accuracy:  0.9130434782608695

In [17]:
def predict_resume_category(resume_text):
    cleaned_text = clean_resume_text(resume_text)
    processed_text = preprocess_text(cleaned_text)
    vectorized_text = tfidf.transform([processed_text])
    prediction = rf_model.predict(vectorized_text)
    return prediction[0]

In [18]:
sample_resume ="""
Python developer with 5 years of experience in building web applications using Django and Flask. Proficient in data analysis and machine learning with libraries like Pandas, NumPy, and Scikit-learn. Strong background in software development and project management.
"""
predicted_category = predict_resume_category(sample_resume) 
print("Predicted Category for Sample Resume: ", predicted_category)

Predicted Category for Sample Resume:  Other

In [19]:
skills = ["python", "java","c++","javascript","html","css","react","nodejs","flask","django","tensordlow","pytorch","machine learning","nlp","data science","sql","mongodb","mysql","git","github","aws","docker","kubernetes","pandas","numpy","scikit-learn"]
print("Skills list created with ", len(skills), " skills.")

Skills list created with  26  skills.

In [20]:
def extract_skills(resume_text):
    resume_text = resume_text.lower()
    found_skills=[]
    for skill in skills:
        if skill.lower() in resume_text:
            found_skills.append(skill)
    return found_skills

In [21]:
sample_resume ="""Python Developer with experience in machine learning and data analysis using libraries like Pandas and NumPy. Proficient in web development with Flask and Django. Skilled in SQL, Git, and AWS. """
skills_found = extract_skills(sample_resume)
print("Skills found in sample resume: ", skills_found)

Skills found in sample resume:  ['python', 'flask', 'django', 'machine learning', 'sql', 'git', 'aws', 'pandas', 'numpy']

In [22]:
job_description = """We are looking for a Python Developer with experience in machine learning and data analysis. The ideal candidate should be proficient in web development using Flask and Django, and have strong skills in SQL, Git, and AWS."""
skills_in_job_description = extract_skills(job_description)
print("Skills found in job description: ", skills_in_job_description)

Skills found in job description:  ['python', 'flask', 'django', 'machine learning', 'sql', 'git', 'aws']

In [23]:
resume_skills = extract_skills(sample_resume)
matched_skills = []
for skill in skills_in_job_description:
    if skill in resume_skills:
        matched_skills.append(skill)
ats_score = len(matched_skills) / len(skills_in_job_description) * 100
print("Matched Skills: ", matched_skills)
print("ATS Score: ", ats_score, "%")

Matched Skills:  ['python', 'flask', 'django', 'machine learning', 'sql', 'git', 'aws']
ATS Score:  100.0 %

In [24]:
import joblib
joblib.dump(rf_model, "rf_model.pkl")
joblib.dump(tfidf, "tfidf_vectorizer.pkl")
print("Model and vectorizer saved as .pkl files.")

Model and vectorizer saved as .pkl files.

In [25]:
loaded_rf_model = joblib.load("rf_model.pkl")
loaded_tfidf = joblib.load("tfidf_vectorizer.pkl")
print("Model and vectorizer loaded successfully.")

Model and vectorizer loaded successfully.